### ISSUE TITLE
How do you derive formula 9?

### ISSUE THREAD

**Issue by JimXiongGM** [cszn/DPSR#5]
can you tell us how do you derive formula 9 with FFT ? thanks very much

**Comment by majedelhelou** [comment]
The tutorial paper below explains how you can go from Eq. (5) in the DPSR paper to Eq. (6-7-8-9). It explains the math behind this approach, and how it can be implemented in practice.

Paper link: [Fourier-Domain Optimization for Image Processing](https://arxiv.org/abs/1809.04187)

**Comment by JimXiongGM** [comment]
thanks a lot ! I have being confused for a fews days, and you do me a big favor.
