### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by dushide** [cszn/DPSR#7]
How to get the low-resolution picture under your code file by using real pictures, as you show the test_01_m_19 picture under x4_m folder and how to get the corresponding .mat file.I want to simulate the entire CBSD68 data set.
Thank you for your answer.

**Comment by cszn** [comment]
https://github.com/cszn/DPSR/blob/master/testsets/BSD68/generate_blurry_LR_images.m

**Comment by dushide** [comment]
I tried to run it but only six empty folders, what changes should I make, thank you and look forward to your reply.

**Comment by dushide** [comment]
I think I found the problem. I ran this program incorrectly in the wrong folder. Thank you for your answer and it helped me a lot.
